name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          git clone --depth=1 https://github.com/LSPosed/MagiskOnWSALocal.git
          cd MagiskOnWSALocal
          cd scripts
          sudo apt install -y whiptail setools lzip wine winetricks patchelf e2fsprogs python3-pip aria2 p7zip-full attr xz-utils unzip
          ./build.sh --help
          ./build.sh --remove-amazon
          ls
      - uses: actions/upload-artifact@v3
        with:
          name: WSA_Win10_retail
          path: libsndfile_MinGW64_Static.7z